### ISSUE TITLE
Command argument -n --cn-neutral-region not updating neutral region

### ISSUE THREAD

**Issue by chrisEisenhartBitscopic** [0xTCG/aldy#65] opened 2023-09-21 16:27 UTC
Hello, hope all is well. I haven noticed that the -n and --cn-neutral-region commands do not update my neutral region. Is there a way I can provide an updated neutral region to the algorithm?

Example commands;

[ceisenhart@localhost foo]$ aldy genotype --cn-neutral-region chr1:10000-20000 -p illumina -g final.bam 
🐿  Aldy v4.4 (Python 3.9.16 on Linux 5.14.0-284.25.1.el9_2.x86_64-x86_64-with-glibc2.34)
   (c) 2016-2023 Aldy Authors. All rights reserved.
   Free for non-commercial/academic use only.
Genotyping sample POC_LAB_1_S19_L00N_R1_001.true.final.bam...
ERROR: gene= cyp2d6, profile= illumina, file= POC_LAB_1_S19_L00N_R1_001.true.final.bam
CN-neutral region 22:42151472-42152258 has no reads. Double check your input file for CYP2D8 (are you using hg19?), or pass an alternative CN-neutral region via -n parameter.

[ceisenhart@localhost foo]$ aldy genotype -n chr1:10000-20000 -p illumina -g final.bam 
🐿  Aldy v4.4 (Python 3.9.16 on Linux 5.14.0-284.25.1.el9_2.x86_64-x86_64-with-glibc2.34)
   (c) 2016-2023 Aldy Authors. All rights reserved.
   Free for non-commercial/academic use only.
Genotyping sample POC_LAB_1_S19_L00N_R1_001.true.final.bam...
ERROR: gene= cyp2d6, profile= illumina, file= POC_LAB_1_S19_L00N_R1_001.true.final.bam
CN-neutral region 22:42151472-42152258 has no reads. Double check your input file for CYP2D8 (are you using hg19?), or pass an alternative CN-neutral region via -n parameter.

I provide an updated copy number region (chr1:10000-20000) and the algorithm still looks for the internally defined region (22:42151472-42152258) then fails when it is not found.  

PS: I've noticed similar behavior when trying to specify hg38 as the genome using --genome hg38. The algorithm still runs with hg19 as if I did not specify.

**Comment by inumanag** [comment] 2023-11-11 17:03
Duplicate of #59 ; will publish the fix soon! Thanks for the report!

**Closed by inumanag** 2023-11-11 17:03 UTC
